# Generated by Django 5.0.2 on 2024-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('usuario', models.TextField()),
                ('fecha_crea', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
